name: alhasan_abo_obaid
description: "Alhasan Portfolio"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  flutter_screenutil: ^5.8.4
  provider: any
  url_launcher: any
  carousel_slider:
  http: ^0.13.4
  cached_network_image: ^3.2.3

  flutter_native_splash: ^2.3.10
  xml: ^6.3.0

flutter_native_splash:
  color: "#FFFFFF"  # Background color
  image: assets/icons/loading.gif  # Splash GIF image
  fullscreen: true
  android: false  # Disable for mobile, only for web
  ios: false
  web: true  # Enable for Flutter Web

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/patterns/
    - assets/fonts/
    - assets/projects/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900